#!/usr/bin/env bash
# Model presets for DeShortcut-Align.
# Source after scripts/common/env.sh. Override any variable before calling a launcher.

: "${MODEL_PRESET:=ds-7b}"

case "$MODEL_PRESET" in
  ds-7b)
    : "${MODEL_PATH:=deepseek-ai/DeepSeek-R1-Distill-Qwen-7B}"
    : "${N_GPUS:=4}"
    : "${HARMFUL_JSON:=$DATASETS_ROOT/raw/risk_data_7B.json}"
    : "${N_HARMFUL:=440}"
    : "${N_BENIGN:=220}"
    : "${TRAIN_DATA_SIZE:=600}"
    : "${VAL_DATA_SIZE:=60}"
    : "${ENABLE_THINKING:=false}"
    : "${SFT_FMT_IDS:=[151646,151644,151645,151648]}"
    : "${SFT_CCR_START:=3}"
    : "${USE_DS_TEMPLATE:=true}"
    # GRPO
    : "${GRPO_TRAIN_BSZ:=8}"
    : "${GRPO_VAL_BSZ:=8}"
    : "${GRPO_MINI_BSZ:=8}"
    : "${GRPO_MICRO_BSZ:=4}"
    : "${GRPO_TP:=2}"
    : "${GRPO_GPU_MEM:=0.6}"
    : "${GRPO_TEMP:=0.9}"
    : "${GRPO_LOGPROB_MICRO:=4}"
    : "${GRPO_REF_LOGPROB_MICRO:=16}"
    : "${GRPO_RHO_MAX:=10}"
    : "${GRPO_APPLY_MODE:=all}"
    : "${GRPO_OFFLOAD:=False}"
    # PPO
    : "${PPO_MINI_BSZ:=4}"
    : "${PPO_MICRO_BSZ:=1}"
    : "${PPO_TP:=2}"
    : "${PPO_GPU_MEM:=0.4}"
    : "${PPO_CRITIC_MICRO:=2}"
    : "${PPO_OFFLOAD:=False}"
    : "${PPO_OPT_OFFLOAD:=True}"
    ;;
  ds-14b)
    : "${MODEL_PATH:=deepseek-ai/DeepSeek-R1-Distill-Qwen-14B}"
    : "${N_GPUS:=8}"
    : "${HARMFUL_JSON:=$DATASETS_ROOT/raw/risk_data_14B.json}"
    : "${N_HARMFUL:=340}"
    : "${N_BENIGN:=160}"
    : "${TRAIN_DATA_SIZE:=450}"
    : "${VAL_DATA_SIZE:=50}"
    : "${ENABLE_THINKING:=false}"
    : "${SFT_FMT_IDS:=[151646,151644,151645,151648]}"
    : "${SFT_CCR_START:=3}"
    : "${USE_DS_TEMPLATE:=true}"
    : "${GRPO_TRAIN_BSZ:=8}"
    : "${GRPO_VAL_BSZ:=4}"
    : "${GRPO_MINI_BSZ:=4}"
    : "${GRPO_MICRO_BSZ:=1}"
    : "${GRPO_TP:=4}"
    : "${GRPO_GPU_MEM:=0.4}"
    : "${GRPO_TEMP:=0.8}"
    : "${GRPO_LOGPROB_MICRO:=1}"
    : "${GRPO_REF_LOGPROB_MICRO:=4}"
    : "${GRPO_RHO_MAX:=5}"
    : "${GRPO_APPLY_MODE:=positive_only}"
    : "${GRPO_OFFLOAD:=True}"
    : "${PPO_MINI_BSZ:=4}"
    : "${PPO_MICRO_BSZ:=1}"
    : "${PPO_TP:=4}"
    : "${PPO_GPU_MEM:=0.4}"
    : "${PPO_CRITIC_MICRO:=1}"
    : "${PPO_OFFLOAD:=True}"
    : "${PPO_OPT_OFFLOAD:=True}"
    ;;
  qwen3-4b)
    : "${MODEL_PATH:=Qwen/Qwen3-4B}"
    : "${N_GPUS:=4}"
    : "${HARMFUL_JSON:=$DATASETS_ROOT/raw/risk_data_7B.json}"
    : "${N_HARMFUL:=440}"
    : "${N_BENIGN:=220}"
    : "${TRAIN_DATA_SIZE:=600}"
    : "${VAL_DATA_SIZE:=60}"
    : "${ENABLE_THINKING:=true}"
    : "${SFT_FMT_IDS:=[151644,151645,872,77091]}"
    : "${SFT_CCR_START:=1}"
    : "${USE_DS_TEMPLATE:=false}"
    : "${GRPO_TRAIN_BSZ:=8}"
    : "${GRPO_VAL_BSZ:=8}"
    : "${GRPO_MINI_BSZ:=8}"
    : "${GRPO_MICRO_BSZ:=4}"
    : "${GRPO_TP:=2}"
    : "${GRPO_GPU_MEM:=0.6}"
    : "${GRPO_TEMP:=0.9}"
    : "${GRPO_LOGPROB_MICRO:=4}"
    : "${GRPO_REF_LOGPROB_MICRO:=16}"
    : "${GRPO_RHO_MAX:=10}"
    : "${GRPO_APPLY_MODE:=all}"
    : "${GRPO_OFFLOAD:=False}"
    : "${PPO_MINI_BSZ:=4}"
    : "${PPO_MICRO_BSZ:=1}"
    : "${PPO_TP:=2}"
    : "${PPO_GPU_MEM:=0.4}"
    : "${PPO_CRITIC_MICRO:=2}"
    : "${PPO_OFFLOAD:=False}"
    : "${PPO_OPT_OFFLOAD:=True}"
    ;;
  *)
    echo "Unknown MODEL_PRESET=$MODEL_PRESET (expected ds-7b, ds-14b, or qwen3-4b)" >&2
    exit 1
    ;;
esac

BENIGN_RL_JSON="${BENIGN_RL_JSON:-$DATASETS_ROOT/raw/agca_benign_rl.json}"
HARMFUL_SFT_JSON="${HARMFUL_SFT_JSON:-$DATASETS_ROOT/raw/STAR-1-harmful-sft.json}"
BENIGN_SFT_JSON="${BENIGN_SFT_JSON:-$DATASETS_ROOT/raw/agca_benign_sft.json}"
